 deploy-dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: ðŸš€ Deploy to DEV
        env:
          URL: ${{ secrets.TOMCAT_URL_DEV }}
          USER: ${{ secrets.TOMCAT_USER_DEV }}
          PASS: ${{ secrets.TOMCAT_PASS_DEV }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to DEV ($URL)"

          echo "ðŸ“Œ Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "ðŸ“Œ Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"

    deploy-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: ðŸš€ Deploy to TEST
        env:
          URL: ${{ secrets.TOMCAT_URL_TEST }}
          USER: ${{ secrets.TOMCAT_USER_TEST }}
          PASS: ${{ secrets.TOMCAT_PASS_TEST }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to DEV ($URL)"

          echo "ðŸ“Œ Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "ðŸ“Œ Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"

 deploy-prod:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: ðŸš€ Deploy to PROD
        env:
          URL: ${{ secrets.TOMCAT_URL_PROD }}
          USER: ${{ secrets.TOMCAT_USER_PROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PROD }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to DEV ($URL)"

          echo "ðŸ“Œ Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "ðŸ“Œ Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"

 deploy-pre:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: ðŸš€ Deploy to PRE
        env:
          URL: ${{ secrets.TOMCAT_URL_PRE }}
          USER: ${{ secrets.TOMCAT_USER_PRE }}
          PASS: ${{ secrets.TOMCAT_PASS_PRE }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to DEV ($URL)"

          echo "ðŸ“Œ Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "ðŸ“Œ Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"            
            
